runtime: python37

# [START handlers]
handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: auto
  secure: always
# [END handlers]

#[START env]
env_variables:
    CLOUD_STORAGE_BUCKET: <your bucket name>
    SESSION_SECRET_KEY: <your session key>
#[END env]
